global:
  marketplace-ami: false
  owner: quickstart@amazon.com
  qsname: quickstart-datalake-47lining
  regions:
    - us-east-1
    - us-west-2
  reporting: true
tests:
  multi-node:
    parameter_input: data-lake-multi-node.json
    template_file: data-lake-master.yaml
    regions:
      - us-west-2
  single-node:
    parameter_input: data-lake-single-node.json
    template_file: data-lake-master.yaml
    regions:
      - us-east-1
