  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: 'DB subnet group'
      SubnetIds:
      - {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetAPrivate'}
      - {'Fn::ImportValue': !Sub '${ParentVPCStack}-SubnetBPrivate'}
  Database:
    DeletionPolicy: Snapshot # default
    UpdateReplacePolicy: Snapshot
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: '5'
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      DBInstanceClass: !Ref DBServerInstanceType
      DBName: wordpress
      Engine: MySQL
      MasterUsername: wordpress
      MasterUserPassword: !Ref DBMasterUserPassword
      VPCSecurityGroups:
      - !Ref DatabaseSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: true
      StorageType: gp2
  DatabaseBurstBalanceTooLowAlarm:
    Condition: HasAlertTopic
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Average database storage burst balance over last 10 minutes lower than 20%, expect a significant performance drop soon'
      Namespace: 'AWS/RDS'
      MetricName: BurstBalance
      Statistic: Average
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: LessThanThreshold
      Threshold: 20
      AlarmActions:
      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref Database
  DatabaseCPUUtilizationTooHighAlarm:
    Condition: HasAlertTopic
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Average database CPU utilization over last 10 minutes higher than 80%'
      Namespace: 'AWS/RDS'
      MetricName: CPUUtilization
      Statistic: Average
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 80
      AlarmActions:
      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref Database
  DatabaseDiskQueueDepthTooHighAlarm:
    Condition: HasAlertTopic
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Average database disk queue depth over last 10 minutes higher than 64, performance may suffer'
      Namespace: 'AWS/RDS'
      MetricName: DiskQueueDepth
      Statistic: Average
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 64
      AlarmActions:
      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref Database
  DatabaseFreeableMemoryTooLowAlarm:
    Condition: HasAlertTopic
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Average database freeable memory over last 10 minutes lower than 64 MB, performance may suffer'
      Namespace: 'AWS/RDS'
      MetricName: FreeableMemory
      Statistic: Average
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: LessThanThreshold
      Threshold: 67108864 # 64 MB in Bytes
      AlarmActions:
      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref Database
  DatabaseFreeStorageSpaceTooLowAlarm:
    Condition: HasAlertTopic
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Average database free storage space over last 10 minutes lower than 2 GB'
      Namespace: 'AWS/RDS'
      MetricName: FreeStorageSpace
      Statistic: Average
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: LessThanThreshold
      Threshold: 2147483648 # 2 GB in Bytes
      AlarmActions:
      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref Database
  DatabaseSwapUsageTooHighAlarm:
    Condition: HasAlertTopic
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Average database swap usage over last 10 minutes higher than 256 MB, performance may suffer'
      Namespace: 'AWS/RDS'
      MetricName: SwapUsage
      Statistic: Average
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 268435456 # 256 MB in Bytes
      AlarmActions:
      - {'Fn::ImportValue': !Sub '${ParentAlertStack}-TopicARN'}
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref Database