  LambdaRole:
    Condition: HasEFSProvisionedThroughput
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: 'lambda.amazonaws.com'
          Action: 'sts:AssumeRole'
  LambdaPolicy:
    Condition: HasEFSProvisionedThroughput
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles:
      - !Ref LambdaRole
      PolicyName: lambda
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action:
          - 'logs:CreateLogStream'
          - 'logs:PutLogEvents'
          Resource: !GetAtt 'LambdaLogGroup.Arn'
  LambdaFunction: # needs no monitoring because it is used as a custom resource
    Condition: HasEFSProvisionedThroughput
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: |
          'use strict';
          const response = require('cfn-response');
          exports.handler = (event, context, cb) => {
            const throughput = parseInt(event.ResourceProperties.ThroughputInMibps, 10);
            const threshold = Math.round(throughput * 1048576 * 600 * 0.9);
            response.send(event, context, response.SUCCESS, {Threshold: threshold});
          };
      Handler: 'index.handler'
      MemorySize: 128
      Role: !GetAtt 'LambdaRole.Arn'
      Runtime: 'nodejs12.x'
      Timeout: 60
  LambdaLogGroup:
    Condition: HasEFSProvisionedThroughput
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/lambda/${LambdaFunction}'
      RetentionInDays: !Ref MasterLogsRetentionInDays
  MaxThroughputCalculator:
    Condition: HasEFSProvisionedThroughput
    Type: 'Custom::MaxThroughputCalculator'
    DependsOn:
    - LambdaLogGroup
    - LambdaPolicy
    Version: '1.0'
    Properties:
      ThroughputInMibps: !Ref EFSProvisionedThroughputInMibps
      ServiceToken: !GetAtt 'LambdaFunction.Arn'