  MaintenanceWindow:
    Type: 'AWS::SSM::MaintenanceWindow'
    Properties:
      AllowUnassociatedTargets: false
      Cutoff: 1
      Duration: 2
      Name: !Ref 'AWS::StackName'
      Schedule: !Ref MaintenanceWindowSchedule
      ScheduleTimezone: !Ref MaintenanceWindowScheduleTimezone
  MaintenanceWindowTarget:
    Type: 'AWS::SSM::MaintenanceWindowTarget'
    Properties:
      ResourceType: INSTANCE
      Targets:
      - Key: InstanceIds
        Values: [!Ref VirtualMachine]
      WindowId: !Ref MaintenanceWindow
  MaintenanceWindowTask:
    Type: 'AWS::SSM::MaintenanceWindowTask'
    Properties:
      MaxConcurrency: '1'
      MaxErrors: '1'
      Priority: 0
      Targets:
      - Key: WindowTargetIds
        Values: [!Ref MaintenanceWindowTarget]
      TaskArn: 'AWS-RunPatchBaseline'
      TaskInvocationParameters:
        MaintenanceWindowRunCommandParameters:
          Parameters:
            Operation: [Install]
      TaskType: 'RUN_COMMAND'
      WindowId: !Ref MaintenanceWindow
  AssociationRunPatchBaselineScan:
    Type: 'AWS::SSM::Association'
    Properties:
      Name: 'AWS-RunPatchBaseline'
      Parameters:
        Operation: [Scan]
      ScheduleExpression: 'rate(1 hour)'
      Targets:
      - Key: InstanceIds
        Values: [!Ref VirtualMachine]