region = "us-east-1"
#assume_role_arn = "arn:aws:iam::152876274589:role/AWSControlTowerExecution"
assume_role_arn = "arn:aws:iam::788562962147:role/onica-sso-OnicaSsoRole-1L47XZZPIVQJ7"
environment = "shared"
tf_dynamodb_lock_table_name = "ttanlab_shared_tfstate_us_east_1"
tf_state_bucket_name = "ttanlab-shared-tf-us-east-1"
